name: Deployment

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write


jobs:
  WindowsSFML:
    runs-on: windows-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1.12.1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DJT_ENABLE_UNITTESTS=OFF -DCMAKE_BUILD_TYPE=Release -DJT_ENABLE_DEBUG=OFF -DJT_ENABLE_DEMOS=OFF .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Copy files
        run: |
          mkdir ${{github.workspace}}/release
          mkdir ${{github.workspace}}/release/release_win
          cp ${{github.workspace}}/build/impl/game_client/Release/*.exe ${{github.workspace}}/release/release_win/
          cp ${{github.workspace}}/build/impl/game_server/Release/*.exe ${{github.workspace}}/release/release_win/
          cp -r ${{github.workspace}}/build/impl/game_client/Release/assets ${{github.workspace}}/release/release_win/

      - name: Create Archive
        uses: thedoctor0/zip-release@0.6.2
        with:
          directory: ${{github.workspace}}/release
          type: 'zip'
          filename: 'release_win.zip'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/release/release_win.zip

  LinuxSFML:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set up system libs
        run: |
          sudo apt update && \
          sudo apt-get install -y \
          xorg-dev \
          libudev-dev \
          libopenal-dev \
          x11-xserver-utils \
          libfreetype-dev \
          libudev-dev

      - name: CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DJT_ENABLE_UNITTESTS=OFF -DCMAKE_BUILD_TYPE=Release -DJT_ENABLE_DEMOS=OFF .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Copy files
        run: |
          export RELEASE_NAME=$(echo "${GITHUB_REPOSITORY}" | sed 's/^[^\/]*\///g')
          mkdir -p ${{github.workspace}}/release/${RELEASE_NAME}_linux
          cp ${{github.workspace}}/build/impl/game_client/game_client ${{github.workspace}}/release/${RELEASE_NAME}_linux
          cp ${{github.workspace}}/build/impl/game_server/game_server ${{github.workspace}}/release/${RELEASE_NAME}_linux
          cp -R ${{github.workspace}}/build/impl/game_server/assets ${{github.workspace}}/release/${RELEASE_NAME}_linux
          cd ${{github.workspace}}/release
          tar -czvf ${{github.workspace}}/release/release_linux-x86_64.tar.gz ${RELEASE_NAME}_linux

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/release/release_linux-x86_64.tar.gz

  Mac_SFML:
    runs-on: macos-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          max-size: 200M

      - name: CMake
        run: |
          cmake \
          -G Ninja \
          -DJT_ENABLE_DEMOS=OFF \
          -DJT_ENABLE_UNITTESTS=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Copy files
        run: |
          export RELEASE_NAME=$(echo "${GITHUB_REPOSITORY}" | sed 's/^[^\/]*\///g')
          mkdir -p ${{github.workspace}}/release/${RELEASE_NAME}_mac
          cp ${{github.workspace}}/build/impl/game_client/game_client ${{github.workspace}}/release/${RELEASE_NAME}_mac
          cp ${{github.workspace}}/build/impl/game_server/game_server ${{github.workspace}}/release/${RELEASE_NAME}_mac
          cp -R ${{github.workspace}}/build/impl/game_server/assets ${{github.workspace}}/release/${RELEASE_NAME}_mac
          cd ${{github.workspace}}/release
          tar -czvf ${{github.workspace}}/release/release_mac.tar.gz ${RELEASE_NAME}_mac

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/release/release_mac.tar.gz
